background {
    monitor =
    path = /home/huyprowow/Pictures/IA.webp
    blur_passes = 1
    blur_size = 3
}

label {
    monitor =
    text = $TIME
    font_size = 70
    font_family = Pixelon
    color = rgba(ffffffee)

    halign = center
    valign = center
    position = 0, 120
}

input-field {
    monitor =
    size = 260, 50
    
     # Glass nền chung
    inner_color = rgba(ffffff15)

    outline_thickness = 2

    # 🟦 Bình thường (glass trắng lạnh)
    outer_color = rgba(ffffff40)

    # 🔴 Sai mật khẩu (glass đỏ mờ)
    outer_color_fail = rgba(ff444488)

    # 🟢 Đúng mật khẩu (glass xanh mờ)
    outer_color_ok = rgba(44ff8888)

    font_color = rgba(ffffffff)

    dots_center = true
    dots_size = 0.28
    dots_spacing = 0.2

    fade_on_empty = false
    halign = center
    valign = center
    position = 0, -50
}
