# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.5

# Window
background_opacity 0.90
window_padding_width 10
confirm_os_window_close 0

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Scrollback
scrollback_lines 5000

# Performance
enable_audio_bell no
visual_bell_duration 0

# Color scheme (clean dark)
foreground #cdd6f4
background #11111b

selection_foreground #11111b
selection_background #cdd6f4

# Cursor color
cursor #f5e0dc
cursor_text_color #11111b

# Tabs (optional)
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

